# install the required packages for the project using conda
# to create the environment run the following command:
# conda env create -f environment.yml

name: sql-report-template
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.10
  - pip
